import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import a1 from '../images/a1.jpg';
import a2 from '../images/a2.jpg';
import a3 from '../images/a3.jpg';
import a4 from '../images/a4.jpg';
import a5 from '../images/a5.jpg';
const AboutSection = ({ handleNavClick }) => {
    return (_jsxs("div", { className: "bg-white p-8 rounded shadow-sm", children: [_jsxs("div", { className: "max-w-3xl", children: [_jsx("h1", { className: "text-3xl font-light mb-4", children: "About Northern Spark Photography" }), _jsx("h2", { className: "text-2xl font-light mb-4", children: "Nisswa's Premier Senior & Family Photography Studio" }), _jsx("p", { className: "mb-4", children: "As a Christian photographer from Brainerd, Minnesota, I bring both faith and artistry to every session. Northern Spark Photography specializes in capturing authentic moments that celebrate God's creation through professional photography services for seniors, families, events, and fashion throughout Minnesota." }), _jsx("p", { className: "mb-4", children: "With over 15 years of experience behind the lens, I've developed an approach that combines natural light, creative composition, and genuine connection to create images that tell your story in a way that's both timeless and contemporary." }), _jsx("p", { className: "mb-4", children: "My journey began in Brainerd, where I discovered my passion for photography, and has led me to serve countless families and individuals throughout central Minnesota, creating lasting memories that reflect both professional excellence and Christian values." })] }), _jsxs("div", { className: "grid grid-cols-3 gap-4 my-8", children: [_jsx("img", { src: a1, alt: "Photography sample 1", className: "w-full h-64 object-cover rounded" }), _jsx("img", { src: a2, alt: "Photography sample 2", className: "w-full h-64 object-cover rounded" }), _jsx("img", { src: a3, alt: "Photography sample 3", className: "w-full h-64 object-cover rounded" }), _jsx("img", { src: a4, alt: "Photography sample 4", className: "w-full h-64 object-cover rounded col-span-2" }), _jsx("img", { src: a5, alt: "Photography sample 5", className: "w-full h-64 object-cover rounded" })] }), _jsxs("div", { className: "mt-8", children: [_jsx("h3", { className: "text-xl font-light mb-4", children: "Why Choose Northern Spark Photography?" }), _jsxs("ul", { className: "list-disc pl-8 mb-6", children: [_jsx("li", { children: "Personalized sessions tailored to your unique vision" }), _jsx("li", { children: "Professional editing and retouching" }), _jsx("li", { children: "Fast turnaround times" }), _jsx("li", { children: "Beautiful, customized products" }), _jsx("li", { children: "Based in Nisswa but available for travel throughout Minnesota" })] }), _jsxs("p", { children: ["Ready to book your session? ", _jsx("button", { onClick: () => handleNavClick('contact'), className: "underline", children: "Contact us today" }), " to get started!"] })] })] }));
};
export default AboutSection;
